from datetime import date, datetime
from zoneinfo import ZoneInfo
from django.core.management.base import BaseCommand
from django.contrib.auth.models import Group, Permission
from django.db import transaction
from hub.models import Citation, Entry, SiteSettings, Source

REVIEWED = date(2026, 10, 2)
PUBLISHED = datetime(2026, 10, 2, 13, 0, tzinfo=ZoneInfo('America/New_York'))

class Command(BaseCommand):
    help = 'Create initial source-backed content and editorial groups. Never overwrite existing entries.'

    @transaction.atomic
    def handle(self, *args, **options):
        SiteSettings.objects.get_or_create(pk=1)
        sources = {}
        source_data = [
            ('eia', 'Energy storage for electricity generation', 'U.S. Energy Information Administration', 'https://www.eia.gov/energyexplained/electricity/energy-storage-for-electricity-generation.php', 'agency', None),
            ('epri', 'Energy Storage Safety', 'Electric Power Research Institute', 'https://energystorage.epri.com/hub/public/en/safety-environment.html', 'research', None),
            ('nyserda', 'Initial findings from the Inter-Agency Fire Safety Working Group', 'NYSERDA', 'https://www.nyserda.ny.gov/About/Newsroom/2023-Announcements/2023-12-21-Governor-Hochul-Announces-Results-of-Fire-Safety-Working-Group', 'agency', date(2023,12,21)),
            ('aps', 'McMicken investigation and technical report', 'Arizona Public Service', 'https://newsroom.aps.com/mcmicken-investigation/', 'operator', date(2020,7,27)),
            ('fsri', 'Four firefighters injured in lithium-ion battery energy storage system explosion — Arizona', 'UL Fire Safety Research Institute', 'https://fsri.org/resource/four-firefighters-injured-lithium-ion-battery-energy-storage-system-explosion-arizona', 'research', None),
            ('esv', 'Statement of technical findings: Victorian Big Battery', 'Energy Safe Victoria', 'https://www.energysafe.vic.gov.au/sites/default/files/2022-12/VBB_StatementOfFindings_FINAL_28Sep2021.pdf', 'agency', date(2021,9,28)),
            ('epa', 'Moss Landing Vistra Battery Fire Response', 'U.S. Environmental Protection Agency', 'https://www.epa.gov/ca/moss-landing-vistra-battery-fire', 'agency', None),
            ('noaa', 'Battery facility fire; Moss Landing, CA', 'NOAA IncidentNews', 'https://incidentnews.noaa.gov/incident/10901', 'agency', date(2025,1,16)),
        ]
        for key, title, publisher, url, kind, published in source_data:
            sources[key], _ = Source.objects.get_or_create(url=url, defaults=dict(title=title, publisher=publisher, source_type=kind, published_date=published, checked_date=REVIEWED))

        def entry(slug, title, kind, summary, body, refs=(), **extra):
            defaults = dict(title=title, kind=kind, summary=summary, body=body, status='published', verification='editorial', checked_date=REVIEWED, published_at=PUBLISHED)
            defaults.update(extra)
            obj, created = Entry.objects.get_or_create(slug=slug, defaults=defaults)
            if created:
                for key, supports in refs:
                    Citation.objects.create(entry=obj, source=sources[key], supports=supports)
            return obj

        entry('woodlawn-proposal', 'The proposed Woodlawn battery storage project', 'page',
              'A place to examine the proposal, the supporting documents, and the questions that need a site-specific answer.',
              '## A record that can be checked\n\nThis resource follows a proposed battery energy storage project in Woodlawn, Bronx. The local project file is being assembled for publication. Capacity, equipment, addresses, and permit status will be attributed to dated original documents as those records are reviewed.\n\n## Start with three questions\n\nWhat equipment and usable energy capacity are proposed for the entire site? Which approvals have actually been issued? What site-specific emergency and operating plans support the application?\n\n## Reading the approval record\n\nA historical portal screenshot is evidence of what the portal displayed on that date. It cannot establish today’s permit status. Review comments, conditions, approvals, and construction milestones should each be recorded separately.\n\n## Follow the evidence\n\nThe Questions section tracks the topics awaiting answers. The Documents section contains source material and agency resources. New local filings will be added after review, with dates and an explanation of what changed.', verification='review')
        entry('battery-storage-basics', 'Battery storage, in plain language', 'page',
              'What a BESS does, why it is used, and the difference between power and stored energy.',
              '## Store now, use later\n\nA battery energy storage system, or BESS, takes in electricity, stores energy, and supplies electricity later. Grid storage can help balance supply and demand and shift electricity to the hours when it is needed.\n\n## MW and MWh answer different questions\n\nMegawatts (MW) describe the rate at which a system can deliver power. Megawatt-hours (MWh) describe an amount of energy. In a simplified example, 10 MWh divided by 5 MW is two hours of output; real operating limits and losses affect the result.\n\n## Potential benefits need local evidence\n\nGeneral grid benefits do not establish the benefit of a particular project. For Woodlawn, ask what services are contracted, how the utility connection works, and whether any neighborhood backup capability is actually designed and approved.', refs=[('eia', 'Definitions of power and energy capacity, and general electricity-storage uses. The numerical example is illustrative.')], verification='documented')
        entry('safety-and-planning', 'Safety & emergency planning', 'page',
              'Questions to connect general safety claims with the equipment, layout, and response plan proposed for this site.',
              '## Ask for the plan behind the claim\n\nA useful public record identifies the applicable equipment, installation drawings, testing, maintenance, and emergency procedures. This page sets out questions for that review; it does not assign a hazard rating to the Woodlawn proposal.\n\n## Equipment and detection\n\nWhat battery chemistry and equipment version will be installed? Which detection and shutdown systems apply? What testing supports the proposed separation distances and configuration?\n\n## Response and access\n\nHow would responders access the site? Who can isolate equipment? How are nearby facilities, access routes, and residents considered? Ask for the written plan and the responsible reviewing agency.\n\n## Communication and recovery\n\nWho informs the community, and how? What determines protective actions? What arrangements cover monitoring, damaged-battery removal, and restoration?\n\n## Learn from the complete record\n\nRead investigation findings and corrective measures together. The incident library includes both adverse outcomes and reported monitoring findings, while explaining limits on comparison.', refs=[('fsri', 'Technical report providing context for questions about emergency response.'), ('esv', 'Technical findings and corrective measures providing context for equipment and commissioning questions.')])
        entry('community-considerations', 'Community considerations', 'page',
              'A framework for examining neighborhood effects without treating assumptions as measured facts.',
              '## Everyday operation\n\nAsk for the noise study, equipment operating schedule, construction plan, vehicle routes, and visual screening drawings. Record the assumptions and the version of the plan being evaluated.\n\n## Emergency disruption\n\nA study radius is a way to organize an analysis. It is not an official evacuation zone. Any map should identify its center, radius, data sources, and counting method. Protective actions in a real incident are determined by the authorities using actual conditions.\n\n## Count like with like\n\nResidents, households, housing units, and buildings are different quantities. Keep Bronx and Yonkers counts separate before adding totals. Describe the dataset date and any gaps.\n\n## Estimates are scenarios\n\nAny cost estimate should state how many people or businesses are assumed to be affected, how long disruption lasts, and what daily cost is used. Present a range and avoid implying the scenario is an expected outcome.\n\n## Include benefits and responses\n\nPublish supported claims of local benefits alongside identified concerns. Attribute the developer’s answers and explain which questions they address.')
        entry('about', 'About this resource & editorial standards', 'page',
              'How the information is selected, labeled, corrected, and kept understandable.',
              '## Purpose\n\nThis is a community information resource about battery storage and the proposed Woodlawn project. It is not an agency publication, a permit determination, or a statement that a company or technology is unsafe.\n\n## Evidence labels\n\nDocumented: a statement supported by the cited record. Attributed statement: what an identified organization or person says. Estimate: a calculation with disclosed assumptions. Awaiting confirmation: information still being checked. Community question / editorial: a question, interpretation, or editorial guidance.\n\n## Sources and dates\n\nPrefer original agency documents, investigations, and technical records. Identify operator statements as such. Show when evidence was reviewed, and distinguish that date from the incident date and the publication date.\n\n## Fair comparisons\n\nThe case library is a selected set of incidents, not a comprehensive database. Differences in equipment, chemistry, age, installation, and operating conditions matter. Incident counts alone do not establish a failure probability.\n\n## Corrections and responses\n\nEditors should preserve the source, explain material corrections, and include relevant documented responses. A missing answer on this site is not proof that a company or agency refused to answer.\n\n## Privacy\n\nPublic pages do not require an account. Editor accounts use session cookies. The optional map contacts OpenStreetMap when loaded. Hosting infrastructure may retain request logs; the site includes no advertising or analytics tracker.\n\n## Website operator\n\nOperator and contact details are pending completion in the site settings before public launch.')

        entry('mcmicken-2019', 'McMicken: responder injuries and investigation', 'incident',
              'A 2019 Arizona incident documented by the system operator and the Fire Safety Research Institute.',
              '## What is documented\n\nAPS reports smoke at its McMicken site on April 19, 2019, followed about three hours later by a catastrophic failure shortly after a door was opened. FSRI published a report on the explosion and four injured firefighters.\n\n## System context\n\nAPS describes a 2 MW / 2 MWh system, integrated by Fluence and in service from March 2017. Read the investigation documents for the technical findings and recommendations.',
              refs=[('aps', 'Incident sequence, system capacity, integrator, and service date.'), ('fsri', 'Report on the explosion and injuries to four firefighters.')],
              verification='documented', event_date=date(2019,4,19), location='Surprise, Arizona', country='United States', manufacturer='Fluence (system integrator)', chemistry='Lithium-ion; subtype not established here', outcome='explosion', latitude=33.63, longitude=-112.37,
              impact='Four firefighter injuries are documented in the FSRI report. This summary does not establish a residential evacuation count.',
              comparison='The event raises questions about responder information and emergency planning. It is not the same installation or equipment as the Woodlawn proposal; do not transfer its outcome or probability to Woodlawn.')
        entry('victorian-big-battery-2021', 'Victorian Big Battery: commissioning fire', 'incident',
              'Energy Safe Victoria examined a fire involving two Tesla Megapacks during commissioning in July 2021.',
              '## Findings and corrective measures\n\nEnergy Safe Victoria reported that two Megapacks were lost in the July 30, 2021 fire. Its most likely initiating cause was a cooling-system leak, with unavailable monitoring and protection functions contributing during commissioning.\n\nThe regulator described pressure testing, leak inspections, monitoring changes, and protection-system changes. It did not object to recommencing commissioning provided the stated measures were in place.',
              refs=[('esv', 'Pages 1–2: event, most likely cause, contributory factors, and measures required for recommencing commissioning.')],
              verification='documented', event_date=date(2021,7,30), location='Moorabool, Victoria', country='Australia', manufacturer='Tesla Megapack', outcome='fire', latitude=-38.06, longitude=144.29,
              impact='Two units were destroyed. The regulator also concluded that the affected units failed safely despite their loss; read that conclusion alongside its account of fire propagation.',
              comparison='This was a commissioning event in an earlier installation. Ask how the proposed equipment version, controls, procedures, and layout incorporate the lessons. Shared branding alone does not establish identical risk.')
        entry('warwick-2023', 'Warwick: fire and environmental findings', 'incident',
              'New York’s December 2023 review included the June 27 Warwick fire and testing near school buildings.',
              '## What the state review says\n\nNYSERDA’s December 21, 2023 release identifies a June 27 fire at Warwick and describes monitoring and sampling information reviewed by the state working group.\n\nAcross the incidents covered by that release, the group reported no injuries and no harmful toxin levels detected in the available analyses. It found no evidence at that time of significant off-site contaminant migration. Those findings are bounded by the data and dates reviewed.',
              refs=[('nyserda', 'December 2023 review, Warwick event date, data reviewed, and the working group’s bounded monitoring conclusions.')],
              verification='documented', event_date=date(2023,6,27), location='Warwick, New York', country='United States', outcome='fire', latitude=41.26, longitude=-74.36,
              impact='The published state summary includes reassuring monitoring findings. This record does not establish an evacuation count, an equipment model, or the complete cause analysis.',
              comparison='A nearby New York case is useful context for asking about response and monitoring. Its results do not prove either an identical exposure or an identical outcome at another site.')
        entry('moss-landing-2025', 'Moss Landing: fire, evacuation, and cleanup', 'incident',
              'Federal records document the January 2025 Vistra fire, local evacuation orders, and EPA’s cleanup role.',
              '## What is documented\n\nEPA identifies a January 16, 2025 fire in Vistra’s 300 MW Moss Landing system. NOAA records evacuation orders and air-plume modeling.\n\n## Recovery after the incident\n\nEPA’s response page describes oversight of battery removal, on-site monitoring, and emergency planning during cleanup. The linked page is a continuing record; later events should be tracked as separate dated records.',
              refs=[('epa', 'Date, affected system, and EPA’s battery-removal and monitoring role.'), ('noaa', 'Evacuation orders, plume modeling, and approximate incident coordinates.')],
              verification='documented', event_date=date(2025,1,16), location='Moss Landing, California', country='United States', chemistry='Lithium-ion; subtype not established here', outcome='fire', latitude=36.8078, longitude=-121.7817,
              impact='Evacuation orders are documented. This summary does not assign a count or duration to them. Cleanup requirements are documented separately from the initial response.',
              comparison='The cited incident involved Vistra’s 300 MW system. It is not evidence that all facilities at Moss Landing, or the Woodlawn proposal, use the same equipment. Local protective-action decisions require site-specific assessment.')

        questions = [
            ('capacity-and-configuration', 'What is the final capacity and equipment configuration?', 'Ask for one reconciled schedule of total MW, usable MWh, equipment count, and equipment model.', 'Please provide the dated equipment schedule and drawings for the entire proposal. Explain any differences between presentation materials and agency filing descriptions, including whether multiple site designations form one integrated facility.'),
            ('current-approvals', 'Which approvals are issued, and which remain outstanding?', 'Distinguish an application, a review comment, and an issued approval.', 'Please list each DOB and FDNY filing, its current status, the date checked, and the approval document where applicable. Explain what must occur before demolition, construction, delivery, commissioning, and operation.'),
            ('emergency-plan', 'How does the emergency plan address this neighborhood?', 'Request a site-specific plan, responsible contacts, and the assumptions used.', 'Please identify responder access, isolation arrangements, notification procedures, and how nearby homes and facilities are considered. Identify who determines protective actions and which agency reviewed the plan.'),
            ('grid-benefits', 'What benefits are expected for the local grid?', 'Ask which services are actually planned and how those benefits are supported.', 'Please identify the utility services or contracts this installation is intended to support. Explain the local need, operating assumptions, and whether neighborhood backup power is part of the approved design.'),
            ('noise-and-operation', 'What will neighbors experience during normal operation?', 'Request the noise study, construction schedule, and maintenance plan.', 'Please provide the acoustic study and its assumptions, including nighttime operation and cumulative equipment noise. Identify construction hours, truck routes, maintenance access, and the process for addressing complaints.'),
            ('cleanup-and-costs', 'Who is responsible for incident recovery and site closure?', 'Ask for documented arrangements for cleanup, decommissioning, and financial responsibility.', 'Please identify the obligations and financial arrangements covering damaged-equipment removal, environmental assessment, restoration, and eventual decommissioning. Distinguish legally required provisions from additional commitments.'),
        ]
        for order, (slug,title,summary,body) in enumerate(questions):
            entry(slug,title,'question',summary,body,order=order)

        for key in ('eia','epri','nyserda','fsri','esv','epa'):
            s=sources[key]
            entry(f'resource-{key}',s.title,'document',f'A reference from {s.publisher}. Read the original source and its date before applying it to a local project.', '## Read the original\n\nThe source link below opens the publisher’s record. It is provided as background, not as a Woodlawn permit or approval.\n\n## Keep the context\n\nReview the scope, date, and limitations of the source. Different installations and historical events may involve different equipment and operating conditions.', refs=[(key,'Original source for this resource listing.')])
        entry('how-to-read-this-record','How to read this community record','update','Start with evidence labels, source dates, and the distinction between a general lesson and a local conclusion.', '## An evidence-led starting point\n\nThis first edition includes explanatory pages, a selected incident library, and a list of site-specific questions. Original local application documents are being prepared for review.\n\n## What is still being checked\n\nCurrent approval status and final equipment details are not established by this first edition. Historical notes remain in the editorial review queue until the original sources can be attached.\n\n## Follow future changes\n\nNew filings, meeting notices, and documented responses can be added as individual records. Material corrections should explain what changed and cite the supporting source.')
        entry('local-packet-review', 'Local project packet — reconcile original records before publication', 'update',
              'Private editorial notes from the community meeting packet. Attach and review the original filings before publishing specific claims.',
              '## Provenance\n\nReviewed from the existing Woodlawn BESS Community Board Meeting Packet. This is a secondary community compilation, not a fresh query of DOB or FDNY.\n\n## Claims to check against originals\n\nThe packet records a company presentation figure of 17.6 MW. It reports four FDNY site descriptions totaling 16 MW and 78.4 MWh, all shown as Revision Required in the September 15, 2026 snapshot. It cites DOB filings X01358531-I1, X01352886-S1, and X01352886-I1 with historical Objections status.\n\nIt records 253 East 233rd Street as the BESS address, with related references to 249 East 233rd and 250 East 234th Street, Bronx Block 3374 and related Lots 11, 12, 13, and 113. It quotes a cost affidavit referring to five MP2XL units, with the manufacturer attribution still to be confirmed.\n\n## Before publication\n\nAttach the original documents. Check redactions. Reconcile capacities and addresses. Obtain a current portal snapshot. Do not publish historic review statuses as current, or treat them as proof of illegality or rejection.', status='draft', verification='review', published_at=None)

        contributor, _ = Group.objects.get_or_create(name='Contributors')
        publisher, _ = Group.objects.get_or_create(name='Publishers')
        contributor.permissions.set(Permission.objects.filter(content_type__app_label='hub', codename__in=['view_entry','add_entry','change_entry','view_source','view_revision','add_citation','change_citation','delete_citation','view_citation']))
        publisher.permissions.set(Permission.objects.filter(content_type__app_label='hub').exclude(codename__in=['delete_entry','delete_source','delete_revision','add_revision','change_revision','delete_sitesettings']))
        self.stdout.write(self.style.SUCCESS('Starter content and editorial groups are ready. Existing content was preserved.'))
