# Generated by Django 5.2.17 on 2026-10-02 18:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import hub.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('kind', models.CharField(choices=[('page', 'Guide / project page'), ('incident', 'Incident'), ('document', 'Document / resource'), ('question', 'Community question'), ('update', 'Update'), ('meeting', 'Meeting')], default='update', max_length=20)),
                ('summary', models.TextField(help_text='A short, plain-language introduction.', max_length=650)),
                ('body', models.TextField(help_text='Plain text. Use a blank line between paragraphs and ## for section headings. HTML is escaped.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Ready for review'), ('published', 'Published')], default='draft', max_length=20)),
                ('verification', models.CharField(choices=[('documented', 'Documented'), ('statement', 'Attributed statement'), ('estimate', 'Estimate'), ('review', 'Awaiting confirmation'), ('editorial', 'Community question / editorial')], default='review', max_length=20)),
                ('checked_date', models.DateField(blank=True, help_text='When the cited evidence was actually checked, not the last edit date.', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='A future date schedules publication. Set automatically on first publication if blank.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_note', models.CharField(blank=True, help_text='Public explanation of a correction or material update.', max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.FileField(blank=True, help_text='Optional PDF, up to 20 MB. Downloads are attachments, and drafts remain private.', upload_to=hub.models.document_path, validators=[hub.models.validate_pdf])),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, help_text='Meetings: America/New_York local time.', null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('manufacturer', models.CharField(blank=True, max_length=160)),
                ('chemistry', models.CharField(blank=True, max_length=120)),
                ('outcome', models.CharField(blank=True, choices=[('fire', 'Fire reported'), ('explosion', 'Explosion reported'), ('other', 'Other failure')], max_length=30)),
                ('impact', models.TextField(blank=True, help_text='Documented injuries, evacuations, closures, or monitoring findings. Include limits.')),
                ('comparison', models.TextField(blank=True, help_text='What this event can and cannot tell us about Woodlawn.')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('question_status', models.CharField(choices=[('open', 'Open question'), ('requested', 'Response requested'), ('partial', 'Partial response'), ('answered', 'Response available')], default='open', max_length=24)),
                ('response', models.TextField(blank=True, help_text='Attribute the response and cite its source. Do not describe a request as sent unless it was sent.')),
                ('response_by', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['order', '-published_at', 'title'],
                'permissions': [('publish_entry', 'Can publish and edit published entries')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Woodlawn Energy Storage', max_length=180)),
                ('subtitle', models.CharField(default='Community Information Center', max_length=180)),
                ('introduction', models.TextField(default='Understand the proposal. Read the evidence. Follow the questions that matter to Woodlawn.')),
                ('operator_name', models.CharField(blank=True, help_text='Who operates this website. Complete before public launch.', max_length=180)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('project_status', models.CharField(default='Current permit status awaiting verification', max_length=180)),
                ('project_status_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('publisher', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('published_date', models.DateField(blank=True, null=True)),
                ('checked_date', models.DateField(default=django.utils.timezone.localdate)),
                ('source_type', models.CharField(choices=[('agency', 'Government / agency'), ('research', 'Research organization'), ('operator', 'Operator / developer'), ('news', 'News report'), ('community', 'Community analysis')], default='agency', max_length=24)),
                ('notes', models.TextField(blank=True, help_text='Public source context, limitations, or corrections.')),
            ],
            options={
                'ordering': ['publisher', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='hub.entry')),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supports', models.CharField(help_text='Which statement this supports; include page/section when useful.', max_length=350)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='hub.entry')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.source')),
            ],
        ),
    ]
